/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author IT-MANAGER
 */
import AppPackage.AnimationClass;
import java.awt.Toolkit;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("214302.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpingresso = new javax.swing.JPanel();
        jlPassword = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbEntrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Fechar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingresso.setBackground(new java.awt.Color(0, 204, 255));
        jpingresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jpingresso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlPassword.setBackground(new java.awt.Color(4, 6, 13));
        jlPassword.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jlPassword.setForeground(new java.awt.Color(4, 6, 13));
        jlPassword.setText("Password:");
        jlPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jpingresso.add(jlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 106, 30));

        jlUsuario.setBackground(new java.awt.Color(4, 6, 13));
        jlUsuario.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(4, 6, 13));
        jlUsuario.setText("Usuário:");
        jlUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jpingresso.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 106, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        jpingresso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 110));

        jtUsuario.setBackground(new java.awt.Color(0, 204, 255));
        jtUsuario.setFont(new java.awt.Font("Geometr415 Blk BT", 1, 14)); // NOI18N
        jtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jtUsuario.setText("Nome do Usuário");
        jtUsuario.setBorder(null);
        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyTyped(evt);
            }
        });
        jpingresso.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(4, 6, 13));
        jpingresso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(4, 6, 13));
        jpingresso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 210, 10));

        jPasswordField1.setBackground(new java.awt.Color(0, 204, 255));
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setText("000000000000000000");
        jPasswordField1.setBorder(null);
        jpingresso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Usuario.png"))); // NOI18N
        jpingresso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 308, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Senha.png"))); // NOI18N
        jpingresso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpingresso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jbEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Entrar.png"))); // NOI18N
        jbEntrar.setBorder(null);
        jbEntrar.setBorderPainted(false);
        jbEntrar.setContentAreaFilled(false);
        jbEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Entrar-On.png"))); // NOI18N
        jbEntrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Entrar-On.png"))); // NOI18N
        jbEntrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Entrar-On.png"))); // NOI18N
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        jpingresso.add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 80, 40));

        getContentPane().add(jpingresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fechar.png"))); // NOI18N
        Fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });
        Fechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FecharKeyReleased(evt);
            }
        });
        jPanel2.add(Fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 70, 40));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minimizar.png"))); // NOI18N
        Minimizar.setText("jLabel5");
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel2.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 60, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharMouseClicked

    private void jtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyTyped
   String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
   }
    }//GEN-LAST:event_jtUsuarioKeyTyped

    private void FecharKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FecharKeyReleased
      
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharKeyReleased

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMouseClicked

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
    
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fechar;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpingresso;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
